// DO NOT EDIT.
// Generated by go2types (https://github.com/dabankio/go2types)
// tslint:disable
// eslint-disable

export namespace types {

  //example/types.WeekDay
  export type WeekDay = "mon" | "sun";

  //example/types.WeekDay2
  export type WeekDay2 = "3" | "4";

  //example/types.T
  export interface T {
    weekday: WeekDay;
    weekday2: WeekDay2;
  }

  //example/types.UserTag
  export interface UserTag {
    tag: string;
  }

  //example/types.User
  export interface User {
    firstname: string;
    secondName: string;
    tags: Array<UserTag> | null;
  }

  //example/user.XTime
  export interface XTime {
  }

  //example/user.PersonEstate
  export interface PersonEstate {
    Amount: number;
    Time: number;
  }

  //example/user.Person
  /*** doc:some document for type person,  */
  export interface Person {
    Name: string | null;
    nickname?: string;
    Age: number;//doc:some document for field age, 
    estates: Array<PersonEstate> | null;
  }

}
