package go2types

import (
	"reflect"
)

// its ok to modified (config)
var (
	DocField       = "doc"                     //find document (of struct) from struct field with name "doc"
	DocTag         = "doc"                     //read document (of struct or of field) from tag "doc"
	CustomTypeMap  = map[reflect.Kind]string{} //go type <-> ts type
	DefaultFileDoc = `// DO NOT EDIT.
// Generated by go2types (https://github.com/dabankio/go2types)
// tslint:disable
// eslint-disable`
)
